CREATE TABLE IF NOT EXISTS downloads (
	level_id TEXT PRIMARY KEY,
	allow INTEGER NOT NULL DEFAULT 0,
);

CREATE TABLE IF NOT EXISTS user_downloads (
	grab_id TEXT PRIMARY KEY,
	allow INTEGER NOT NULL DEFAULT 0,
);
